name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  # Changes

  $CHANGES

  # Contributors
 
  $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
    collapse-after: 5

version-resolver:
  major:
    labels:
      - "type: breaking"
  minor:
    labels:
      - "type: feature"
      - "type: enhancement"
  patch:
    labels:
      - "type: bug"
      - "type: fix"
      - "type: bugfix"
      - "type: maintenance"
      - "type: documentation"

exclude-labels:
  - "skip-changelog"